---
title: 'UGIC R Workshop (May 06 2024)'
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author:
  - Simon Brewer^[University of Utah, simon.brewer@geog.utah.edu]
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: flatly
    df_print: paged
    number_sections: false
    toc: false
    toc_float: false
---

# Installation instructions

Tips on installing R and RStudio [here][install]

# Agenda

- 8:30 – 9:00: Introduction to the R language and software 
- 8:30 – 10:00: [Introduction to R][intro_R] (hands on)
  - Getting used to the interface
  - Basic data input/output
  - Data manipulation with `dplyr`
  - Simple plotting with `ggplot2`
  - Simple statistical analysis
- 10:00-10:30: [Spatial data in R 1][spatial1]
  - `sf` objects
  - Coordinate reference systems
  - Manipulating spatial data
  - Plotting with **ggplot2**
- 10:30-11:00: Break
- 11:00-12:30: [Spatial data in R 2][spatial2]
  - Raster data with **terra**
  - Making maps (`tmap` and `leaflet`)
- 12:30-1:30: Lunch
- 1:30-2:30: Using R for data science 1 (hands on)
  - Brief introduction to data science
  - Building a simple machine learning model
- 2:30-3:00 Break
- 3:00-4:00: Using R for data science 2 (hands on)
  - Machine learning workflows (preprocessing, variable selection)
  - Assessing machine learning models
- 4:00-5:00: Wrap-up, discussion etc

- [Introduction to R][intro_R]

# Data

All files for the hands-on exercises can be found here LINK DEAD

[install]: https://simonbrewer.github.io/ugic-intro-r/UGIC_Workshop_00_Installation.html
[intro_R]: https://simonbrewer.github.io/ugic-intro-r/UGIC_Workshop_01_Intro_R.html
[spatial1]: https://simonbrewer.github.io/ugic-intro-r/UGIC_Workshop_02_Spatial_Data_1.html
[spatial2]: https://simonbrewer.github.io/ugic-intro-r/UGIC_Workshop_02_Spatial_Data_2.html
